### ISSUE TITLE
"Alexa, exit" doesn't work

### ISSUE THREAD

**Issue by sharadagarwal** [OneBusAway/onebusaway-alexa#107]
**Summary:** 

When I launch OneBusAway, the screen shows "When you're ready to quit, try "Alexa, exit"". But that doesn't work. It doesn't exit. I have to wait for it to timeout.

**Steps to reproduce:** 

1. Alexa, launch OneBusAway.
2. Alexa, exit.

**Expected behavior:** 

Take me back to the Alexa home screen.

**Observed behavior:** 

No change. OneBusAway is still in the foreground.

**Device:** 

Echo Show

**Audio or video:** 

![32971173-e20be5d6-cba0-11e7-99f6-81163013fdaa](https://user-images.githubusercontent.com/5649639/32971378-da425aa0-cba1-11e7-8ad7-33ba7b2bf720.JPG)

**Comment by sharadagarwal** [comment]
Please ignore the UFO hovering in the top right, and please excuse the potato quality picture.

**Comment by barbeau** [comment]
@sharadagarwal Thanks for reporting this!  Lamp looks like one in my house :).  When did you notice this problem?  Trying to figure out if it's recent and might be something quickly patched by Amazon or if it's been a problem of longer duration.

So we support both the `AMAZON.CancelIntent` and `AMAZON.StopIntent`:
https://github.com/OneBusAway/onebusaway-alexa/blob/master/interaction%20model/schema.json#L9

This should support the standard interactions to exit a skill, as discussed in:
https://developer.amazon.com/docs/custom-skills/standard-built-in-intents.html#about-canceling-and-stopping

However, looking at these docs, very strangely the utterance "exit" isn't listed as an example supported phrase (even through the word "exit" is used extensively in the documentation describing what the skill does when responding to the above intents).

Example supported utterances mapped to the `CancelIntent` and `StopIntent` are "stop", "off" "shut up", "cancel", "never mind", and "forget it".  As a workaround, any of these words should definitely exit the skill.

I'm guessing this is a disconnect between the team doing the UI for Echo Show and those that control the utterances mapped to the `CancelIntent` and `StopIntent`.  I find it hard to believe that "exit" didn't make the design list as a supported utterance for these intents, so maybe it's a bug.

Either way, it's a horrible user experience.  I'll see if I can track down whether this is a bug and "exit" should be supported (in which case we could wait for a fix, if this hasn't been going on for a while), or whether it's just an omission for the standard exit intents, in which case we can add it as a custom utterance.

**Comment by sharadagarwal** [comment]
On a hunch, I went to my Echo Show settings and forced an update, and then tried again. It now works! It must have been a bug that manifests on older versions of the Echo software. If someone else experiences this problem, I recommend they force an update.

**Comment by barbeau** [comment]
Glad that worked, thanks for the update!
