### ISSUE TITLE
Respond to "Alexa, when is the next bus?"

### ISSUE THREAD

**Issue by mkfmnn** [OneBusAway/onebusaway-alexa#108]
**Summary:** 

OneBusAway on the Echo is able to respond to some phrases without being explicitly invoked by name, but there are other phrases that Alexa seems to know are about public transit but doesn't send to OneBusAway. 

**Steps to reproduce:**

Say "Alexa, *what* is the next bus" or "Alexa, *when* is the next bus".

**Expected behavior:** 

In both cases, Alexa should respond, "Okay, OneBusAway" and then give the stop schedule information. 

**Observed behavior:** 

Alexa only works with the first phrase; for the second, it responds, "To find public transportation skills and more, please go to the skills section of the Alexa app."

**Device:** 

Echo (1st gen)

**Audio or video:** 

can't upload at the moment, let me know if this would be helpful

**Comment by barbeau** [comment]
Thanks @mkfmnn!  I'm not sure this is possible given today's Alexa interface for 3rd party skills, but I'll take a look to see if anything has changed since I last reviewed it.  Do you know if any 3rd party skills respond to this same type of generic query (especially any other transit/bus skills)?

**Comment by mkfmnn** [comment]
After looking into this more I think that this is not something that skill developers can control, despite the initial response I received from Amazon CS.

**Comment by barbeau** [comment]
Thanks for taking a closer look!
