### ISSUE TITLE
Certification failure - person<->user transition within conversation

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#115]
**Summary:** 

Our submission of release [v1.2.0](https://github.com/OneBusAway/onebusaway-alexa/releases/tag/v1.2.0) was kicked back from Amazon skill certification with the below issues.

>Issues with skill in English (Australia)
>
>__________________________________________________________
>When using skills personalization, your skill must respond appropriately to requests without a personId in a session started with a request containing a personId.
>
>Steps To Reproduce:
>
>User: "Alexa,ask one bus away my home is tampa bay"
>Skill: "Ok Tom, we found the Tampa Bay region near you. What's your stop number?"
>User: "six nine six eight"
>Skill: "Ok Tom, your stop number is 6968 in the Tampa Bay region. Great. I am ready to tell you about the next bus......North to University Area is departing in 26 minutes Route 8 West to Downtown is arriving in 64 minutes "
>
>Please note that while switching from a recognised user to an unrecognised user by saying “6968”, the skill still refers to the Recognised user’s name as “ Ok Tom” , kindly ensure that the skill behaves appropriately for requests made by unrecognised user’s .
>
>Expected: The skill should stop using the original user’s name.
>
>Please refer to our documentation : https://developer.amazon.com/docs/custom-skills/test-troubleshoot-personalization.html on how to test and troubleshoot personalization for your skill.
>When using skills personalization, your skill must respond appropriately to requests with a personId in a session started with a request not containing a personId.
>
>Steps to Reproduce:
>
>User: “Alexa,open one bus away”
Skill: “Welcome to OneBusAway! Let''s set you up. You''ll need your city and your stop number. The stop number is shown on the placard in the bus zone, on your transit agency''s web site, or in your OneBusAway mobile app. In what city do you live?”
User: "my city is tampa bay"
Skill: "Ok, we found the Tampa Bay region near you. What's your stop number?"
>
>Please note that while switching from an unrecognised user to a recognised user by saying “my city is tampa bay” , the skill fails to identify the Recognised user and continues to behave as if the unrecognized user is still using the skill.
>
>Expected: The skill should state that it can identify the user and it needs to start over, and returns to an earlier step such as the welcome prompt.
>
>Please refer to our documentation : https://developer.amazon.com/docs/custom-skills/test-troubleshoot-personalization.html on how to test and troubleshoot personalization for your skill.

**Steps to reproduce:** 

See above

**Expected behavior:** 

See above

**Observed behavior:** 

See above

**Device:** 

Amazon skill certification

**Comment by victormocz** [comment]
This is the expected behavior after personalization.
We should resolve this issue as it is not a blocker for certification anymore

**Comment by barbeau** [comment]
Yes, we resubmitted this to certification again unchanged and it was accepted the 2nd time, so we can close this.
