### ISSUE TITLE
Allow setting city via single word answers

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#12]
Currently the skill asks "What is your city?".  My response was "Seattle".  

This doesn't currently work, as the skill currently requires the below type of [utterances](https://github.com/OneBusAway/onebusaway-alexa/blob/master/interaction%20model/utterances.txt#L1):
~~~
city is {cityName}
my city is {cityName}
my home is {cityName}
i live in {cityName}
~~~

@philipmw is it possible to support single-word answers like this (e.g., just `SetCityIntent {cityName}`), or does it need to be mentioned in context of other words in an utterance?

**Comment by philipmw** [comment]
To the best of my knowledge, the SDK would allow only one intent to enjoy the "single-word" status. For example, we can have an utterance entry like `SetCityIntent {cityName}` but then we would not be able to have `SetStopId {stopId}` since then Alexa won't be able to distinguish between them. (Unless she distinguishes by type of variable.)

**Comment by barbeau** [comment]
I'm not sure what changed, but it seems to recognize when I just say "Tampa" now.

@philipmw Could you please give this a try as well to confirm?  If it works we can close out this issue.

**Comment by barbeau** [comment]
I went through UX bootstrap again today and it recognized "Tampa", so I'm going to close this.  If we see otherwise we can reopen.

**Comment by barbeau** [comment]
Looks like this is a problem again, but this time it's mapping single word city answers to the GetArrivalsIntent.  Adding `SetCityIntent {cityName}` to utterances seems to fix this - will push a fix shortly.

**Comment by barbeau** [comment]
This still doesn't work for Atlanta - I'm assuming because the three syllables are too close to some of the SetCityIntent utterances.  If I remove some of those, it seems to work fine.  Will push fix shortly.
