### ISSUE TITLE
Can't enable experimental regions

### ISSUE THREAD

**Issue by marcusraylewis** [OneBusAway/onebusaway-alexa#124]
**Summary:** 

I cannot set OneBusAway Experimental Region to New York City

**Steps to reproduce:** 

Me: "Alexa One Bus Away" 
Alexa: Welcome to One bus away! Let's set you up! You'll need your city and your stop number. The stop number is shown on the placard in the bus zone, on your transit agency's city website or on your One Bus Away Mobile App! In what city do you live?
Me: "Alexa set experimental region to New York City"

**Expected behavior:** 

I expected the dialog associated with setting NYC as an experimental city

**Observed behavior:** 

Alexa loops back to welcome to One Bus Away...Alexa: Welcome to One bus away! Let's set you up! You'll need your city and your stop number. The stop number is shown on the placard in the bus zone, on your transit agency's city website or on your One Bus Away Mobile App! In what city do you live?

**Device:** 

Echo Dot

**Audio or video:** 

Sent Dropbox file with audio recording.

**Comment by barbeau** [comment]
@marcusraylewis Can you please try the following exactly:
1. "Alexa, open OneBusAway"
2. Say "Tampa" for city
3. Say "6497" for stop number

This should set you up with a valid stop in Tampa. Then, try exactly:
4. "Alexa, ask OneBusAway to enable experimental regions"

This should enable experimental regions. Then, try exactly:
5. "Alexa, ask OneBusAway to set my city to New York City"

Alexa should say "Ok, we found the MTA New York City region near you. What's your stop number?"

I'm wondering if you need to first set up a valid production region and stop number before enabling experimental regions.

If the above doesn't work, please let me know exactly where it stops working and what the response is.

**Comment by marcusraylewis** [comment]
Mr, Barbeau,

I was able to successfully set NYC as an experimental region given the steps that you clearly outlined. thank you very much for making that happen.  I do have a new issue whereby the data that is coming to OneBusAway is inaccurate. The GTFS data is not  is "based on the schedule" and needs to be updated. Any help or steps to this is appreciated.

**Comment by barbeau** [comment]
@marcusraylewis Thanks for the update! Good to know. For the NYC info, let's continue the discussion back at https://github.com/OneBusAway/onebusaway-alexa/issues/123. In that issue, could you explain more about what you expect to hear, and what you actually hear?
