### ISSUE TITLE
Arrival Times Incorrect "Based on the Schedule"

### ISSUE THREAD

**Issue by marcusraylewis** [OneBusAway/onebusaway-alexa#126]
Summary: The Bus arrival times are incorrect and says "Based on the schedule" after the incorrect bus time notification is announced

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:**  

Alexa Open One Bus Away

**Expected behavior:** 

Expected correct arrival time

**Observed behavior:** 

The times are very inaccurate and different from other apps that d carry more precise information

I asked Alexa  to open bus time and she begins to call out times for my bus stop routes. She said the next S90 will arrive in 51 mins based on the schedule. I opened another bus app that said one minute and the bus was at the stop in one minute. The bus schedule time that Alexa provides is not correct and is in need of updating.

**Device:** 

Amazon App, Amazon flex and Amazon echo dot

**Audio or video:** 

Please provide links to audio or video of the issue (e.g., a YouTube link)

**Comment by barbeau** [comment]
@marcusraylewis Is this for the NYC experimental region (https://github.com/OneBusAway/onebusaway-alexa/issues/123)?

**Comment by marcusraylewis** [comment]
I neglected to mention that this is indeed the NYC Experimental Region.

**Comment by barbeau** [comment]
@marcusraylewis Ok, thanks - let's continue the discussion at https://github.com/OneBusAway/onebusaway-alexa/issues/123 then to keep all the NYC-specific info in the same place. Could you copy/paste your first post above at the bottom of the https://github.com/OneBusAway/onebusaway-alexa/issues/123 thread?
