### ISSUE TITLE
Can you please include the DFW area in Texas as a supported region?

### ISSUE THREAD

**Issue by vanichitiprolu** [OneBusAway/onebusaway-alexa#133]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

How can we reproduce the issue?

**Expected behavior:** 

What did you expect the skill to do?

**Observed behavior:** 

What happened instead?  Describe your issue in detail here.

**Device:** 

What is the make and model of the Alexa device (e.g., Amazon Echo) that you encountered this on?

**Audio or video:** 

Please provide links to audio or video of the issue (e.g., a YouTube link)

**Comment by barbeau** [comment]
@vanichitiprolu Thanks for reaching out! OneBusAway is an open-source software project that is maintained by the Open Transit Software Foundation (https://opentransitsoftwarefoundation.org/). Under this model, transit agencies deploy the open-source OBA server software (https://onebusaway.org/transit-agency-resources/) at their own agency, which makes their data available via OBA Alexa, iOS, Android, and more.

I'd strongly encourage you to reach out to your local transit agency in DFW, Texas and ask them to support OBA for your community. They can read more about this at the above link, and I'm happy to answer any questions they may have.
