### ISSUE TITLE
Write unit tests for speechlets

### ISSUE THREAD

**Issue by philipmw** [OneBusAway/onebusaway-alexa#18]
I have not been able to write effective unit tests with Mockito, because OneBusAway classes are `final`. Mockito is unable to mock `final` classes. Instead, I propose switching to [JMockit](http://jmockit.org/).

**Comment by barbeau** [comment]
:+1:

**Comment by philipmw** [comment]
I am gonna close this issue because I think the referenced PR addresses it for the most part. We have basic tests. A potential future issue would be to increase code coverage.
