### ISSUE TITLE
No voice response when no upcoming arrivals

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#22]
Currently if there are no upcoming arrivals for a bus stop Alexa says nothing in response to "Open OneBusAway".

We should change this to say "There are no upcoming arrivals in the next X minutes."

**Comment by philipmw** [comment]
Working on it.

**Comment by barbeau** [comment]
Fixed via https://github.com/OneBusAway/onebusaway-alexa/pull/25
