### ISSUE TITLE
Integrate with coveralls.io

### ISSUE THREAD

**Issue by philipmw** [OneBusAway/onebusaway-alexa#24]
[Coveralls.io](http://coveralls.io) helps with test quality by measuring code coverage. Like Travis CI, it is free for open-source projects. I'd like us to integrate with it.

I would start with [these instructions](http://softwarecave.org/2014/02/01/using-junit-jacoco-and-maven-for-code-coverage/) for integrating JUnit, Jacoco, and Maven. Then we would add an existing Maven plugin that submits the Jacoco report to Coveralls using their API.

**Comment by barbeau** [comment]
:+1:

**Comment by philipmw** [comment]
@barbeau, can you either sign up this project on coveralls.io, or give me access to do so?

**Comment by barbeau** [comment]
Ok, should be all set, I just signed up.  Let me know if you need anything else, or have problems accessing the account.

**Comment by barbeau** [comment]
Fixed via https://github.com/OneBusAway/onebusaway-alexa/pull/26
