### ISSUE TITLE
Setting a city is broken

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#42]
Setting a city no longer works after going through the initial UX bootstrap.

**Steps to reproduce:**

1. Do the initial setup (e.g., Tampa Bay region, stop 3105).
2. Say "Alexa, ask OneBusAway to set my city to Seattle"

**What I hear:**

* Alexa - "Ok, I found the Puget Sound region near you.  What's your stop number?
* Me - "6497"
* Alexa - "Ok, your stop number is 6497 in the Tampa Bay region. Great.  I am ready to tell you about the next bus."

...and my city/region doesn't change.

** What I expect:**

Alexa should say:

* Alexa - "Ok, your stop number is 6497 in the **Puget Sound** region. Great.  I am ready to tell you about the next bus."

...and my region/stop number should change.

**Cause:**

I believe this is happening because starting in https://github.com/OneBusAway/onebusaway-alexa/pull/41 we are always writing the persisted user data to the session variables - I believe in the above case, we're overwriting the existing city/region session variable that was set by the user in the same session.

I'm working on a fix.

**Comment by philipmw** [comment]
Wow, nice find.
