### ISSUE TITLE
Create UX flow documentation

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#45]
Amazon has requested UX flow documentation as part of the skill review process.

I've started it here in [this Google Drawing](https://docs.google.com/drawings/d/1TprMxlCym1Nn7LvDvH_Qqh7q6t0iDtRJgHwhPdQk5Vs/edit?usp=sharing).

**Comment by philipmw** [comment]
Thanks for opening this issue. I will try to do this later today.

**Comment by philipmw** [comment]
@barbeau, any particulars on what they want (or don't want) to see?

**Comment by barbeau** [comment]
They mainly just need to be able to validate what the skill actually does against what we expect it to do (flow diagram).  Basically a visual version of unit tests, although not as detailed.

**Comment by philipmw** [comment]
Ok, I think it's ready to go.

**Comment by barbeau** [comment]
Awesome, thanks!  I'll take a final look tomorrow and then send to Alexa team.

**Comment by barbeau** [comment]
Just took a quick look - we still need to reflect that we allow the user to set/get city and stopId, so they can test this feature as well.

**Comment by barbeau** [comment]
@philipmw I've knock out get city, get stop, and help.  Any chance you could get to set city/stop tonight?

**Comment by philipmw** [comment]
Working on it.

**Comment by philipmw** [comment]
All righty.
