### ISSUE TITLE
Improve usability of arrival info

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#49]
From Amazon:

>When we read out the times they come by fast. Can we also add a repeat intent? If you do not have time for that, can we at least add a pause between each time slot?

**Comment by barbeau** [comment]
To clarify, from Amazon:

>The slight pause I am referring to would be a period, space and end quote so that it sounds more natural. Not talking about using SSML or anything more complex. For example, `var speechOutput = "I will ask you " + GAME_LENGTH + " multiple choice questions. Respond with the number of the answer."`

**Comment by barbeau** [comment]
Working on the repeat intent...

**Comment by ganeshgella** [comment]
To reduce the output size for arrivals, should we add duration to arrivals intent ?

Currently one of the arrivals intent is as below,
>> GetArrivalsIntent for arrivals
How about an additional one like,
>> GetArrivalsIntent for arrivals in next {time_slot} minutes

**Comment by barbeau** [comment]
@ganeshgella that's a good idea - can you add that to the ux issue for milestone v1.1?  We are trying to get v1.0 out the door.
