### ISSUE TITLE
Supported commands/questions from user for v1.1

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#6]
From https://github.com/OneBusAway/onebusaway-alexa/issues/3#issuecomment-167388566:
- > I'd love also to support several bus stops (for example, oftentimes there are multiple stops within 0.2 miles, and the customer alternates between them depending on the destination),
- I'd also like to see the command to "Get arrivals for stop (insert stop_code here)"
- ~I would also like to support disambiguating stops with the same stop_code - maybe enumerate them like "Say one for x, two for y...".  See https://github.com/OneBusAway/onebusaway-alexa/issues/53.~  EDIT - This is done.

**Comment by anjishnu** [comment]
When is this going to be published?

**Comment by barbeau** [comment]
v1.0 should be soon.  I plan to start the Amazon review process this week.

**Comment by barbeau** [comment]
Closing this out - we're now tracking features in individual issues with assigned milestones.
