### ISSUE TITLE
Yes/no response isn't recognized when disambiguating stops

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#87]
**Summary:** 

Report in https://github.com/OneBusAway/onebusaway-alexa/pull/83#issuecomment-252276266 via user:

> I have the same issue that barbeau had. When the app reads me the different stops and I say "yes" I get
> 
> "I could not locate a OneBusAway region near No, the city you gave..."

**Steps to reproduce:** 
1. Set region to Tampa
2. Set stop to `3105`.
3. When prompted "Did you mean stop X", say "yes" or "no"

**Expected behavior:** 

Select the stop (if "Yes"), or skip to the next stop (if "No")

**Observed behavior:** 

Alexa recognizes "Yes" or "No" as a city name and says "I could not locate a OneBusAway region near No, the city you gave..."

**Device:** 

Reproduced by user on all attempts on Echo and Dot.  I couldn't reproduce this using Roger.

**Comment by vikram31291** [comment]
Investigating this issue

**Comment by vikram31291** [comment]
When I try this, I get " OneBusAway could not locate your stop number.  Tell me again, what is your stop number?"

Is there a stop number other than "three one zero five" to try?

**Comment by barbeau** [comment]
@greenwoodcm what region and stop ID were you using to reproduce this?

**Comment by howaboutudance** [comment]
same issue... and example is #167 in pudget sound, it pulls up olympia transit center and another in seattle

**Comment by vikram31291** [comment]
Need to try on my own Echo Dot, but can't in the test environment.

**Comment by greenwoodcm** [comment]
This happens for me using stop 6050 in the Puget Sound region.  It correctly asks me to disambiguate the stop and when I say "Yes" on the correct stop it goes back to region selection.

I get this behavior for both an Echo and an Echo Dot.

**Comment by barbeau** [comment]
Finally got a new Echo Dot.  Strangely,  I can't repro this with Tampa and 3105 and Yes, or Puget Sound and 6050 and Yes.

**Comment by barbeau** [comment]
My Dot software version is 561179520.

**Comment by jswedler** [comment]
I ran into this problem as well, with Puget Sound, 4010, Yes. 

I decided to pull the code and set up my own instance of the app to try to debug the problem, but when I did, it successfully set my stop.

I _was_ able to reproduce the bug by going into the Alexa Skill configuration (from [step 4](https://github.com/OneBusAway/onebusaway-alexa#4-set-up-alexa-skill)) and deleted AMAZON.YesIntent and AMAZON.NoIntent from the Intent Schema. Was the Intent Schema updated when the Lambda function was?

**Comment by barbeau** [comment]
@jswedler Thanks for taking time to debug this!   So after looking at this more I think the last submission to Amazon Alexa certification was corrupted.  The app was stuck in the "Certification" state for around 3 weeks, and I'd been pinging Amazon about it but gotten nothing back. Now,  it looks like the skill reset and is no longer in Certification and is back to Development, but under the Live version the old Intent Schema is showing without Yes and No Intent. So something definitely went wrong.   I've reached out to Amazon and will post back when I hear more.

**Comment by barbeau** [comment]
Also, I just submitted to Certification again with the most recent Intent Schema.  I'll post again when I see it go live, and hopefully the issue will then be fixed!

**Comment by barbeau** [comment]
Somethings is definitely wrong - skill got reset back to Development state again without any feedback from Certification team.  Trying to follow up with Amazon again - last few times have been radio silence.

**Comment by barbeau** [comment]
Alright, looks like latest certification messages were being sent to the original Amazon account holder (originally created for Fire Phone) instead of mine.  That's fixed, so I'm now getting certification messages, and the skill is failing certification (frustratingly due to behavior that currently exists in production -  https://github.com/OneBusAway/onebusaway-alexa/issues/93).  So this issue is caused by webapp being updated with new logic for disambiguating stops but the Intents were kicked back due to certification.  I'll leave this open until https://github.com/OneBusAway/onebusaway-alexa/issues/93 is fixed and skill passes certification.

**Comment by barbeau** [comment]
I just submitted v1.0.9 (https://github.com/OneBusAway/onebusaway-alexa/releases/tag/v1.0.9) for certification, which fixed #94, which was the reason for the last certification failure.  Fingers crossed that this makes it into production.

**Comment by barbeau** [comment]
Just got notification that new version passed certification and should now be live.   Could anyone who experienced this issue give it a try and report back?

**Comment by jswedler** [comment]
It works for me now. (Puget Sound, 4010)

**Comment by barbeau** [comment]
@jswedler Great!  I'm going to close out this issue and we can reopen if anyone else is still experiencing it.  Thanks to everyone for their patience while we tracked down the problem.
