### ISSUE TITLE
One of the prompts says "Alexa"

### ISSUE THREAD

**Issue by suewhite** [OneBusAway/onebusaway-alexa#88]
**Summary:** 

When setting up the city and stop number, the app says "Alexa," causing the device to listen.

**Steps to reproduce:** 

Set up this app on any Alexa device for the first time.

**Expected behavior:** 

Gather user data for city, bus stop, etc. without stopping to listen to itself.

**Observed behavior:** 

The device says "Alexa" and then listens because it heard itself say that word.

**Device:** 

all Alexa devices that are set with the wake word as "Alexa" which is the default.

**Audio or video:** 

Please provide links to audio or video of the issue (e.g., a YouTube link)

**Comment by barbeau** [comment]
Interesting, this definitely didn't happen before we launched the skill, tested extensively in an Echo.  I wonder is this is the result of a firmware or server-side update.   What device have you seen this on?

**Comment by suewhite** [comment]
This was on an Echo Dot, software version 564133020. I should clarify that under "Device" on my issue, I said "all" -- and that was a (maybe bad) assumption on my part. Funny bug!

**Comment by barbeau** [comment]
Fixed via https://github.com/OneBusAway/onebusaway-alexa/pull/90.

**Comment by barbeau** [comment]
Finally got a new Echo Dot - strangely,  I can't repo this on my device.   Maybe it depends on environmental acoustics.

**Comment by barbeau** [comment]
My Dot software version is 561179520.
