### ISSUE TITLE
On bootstrap capture initial stop if provided by user

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#95]
**Summary:** 

From https://github.com/OneBusAway/onebusaway-alexa/issues/93 - If the user initially invokes the skill by setting their stop number, we should capture that, instead of asking for their stop number again after setting their region.

Certification feedback:

>When attempting to invoke the skill with your third example phrase, the skill returns a non- contextualized response. The example phrases must function without error since these are interactions that users are most likely to try.   Please see test case 3.1 from our Submission Checklist for guidance on example phrases.

**Steps to reproduce:** 

Reset skill so no region is set.

User: “Alexa, ask OneBusAway to set my stop to 6497”

Skill: “Welcome to OneBusAway! Let's set you up. You'll need your city and your stop number. The stop number is shown on the placard in the bus zone, on your transit agency's web site, or in your OneBusAway mobile app. In what city do you live?”

User: “Tampa”

**Expected behavior:** 

User: “Ok, your stop number is 6497 in the Tampa Bay region...”

We should also change the initial prompt text to recognize that the user has already provided their stop number.

**Observed behavior:** 

User: “Ok, we found the Tampa Bay region near you.  What's your stop number?”

**Device:** 

Certification feedback

**Comment by jswedler** [comment]
I've submitted PR #96 for this issue.
